version: "3.2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - itau

  api:
    build: ./twitter-api/.
    ports:
      - "3333:3333"
    environment:
      MONGO_URI: mongodb://mongo:27017/caseitau
    links:
      - mongo
    networks:
      - itau
    depends_on:
      - mongo

  frontend:
    build: ./twitter/.
    ports:
      - "80:8080"
    environment:
      URL: http://api:3333
    links:
      - api
    networks:
      - itau
    depends_on:
      - api
  sync:
    build: ./twitter-sync/.
    environment:
      MONGO_URI: mongodb://mongo:27017/caseitau
    links:
      - mongo
    networks:
      - itau
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - api
    networks:
      - itau
    links:
      - api

  grafana:
    image: jgabrieltec/grafana-itau
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - itau
    links:
      - prometheus

  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    image: jgabrieltec/elasticsearch-itau:latest
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - itau
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      - itau

    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    # image: docker.elastic.co/kibana/kibana:7.5.1
    image: jgabrieltec/kibana-itau:latest
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - itau

  logspout:
    image: bekt/logspout-logstash
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000

    networks:
      - itau

networks:
  itau:
    driver: bridge

volumes:
  elasticsearch:
